In [2]:
import yfinance as yf

# Récupération des données sur le bitcoin
df_BTC = yf.download('BTC-EUR', start='2013-01-01')

[*********************100%***********************]  1 of 1 completed


In [129]:
df_BTC_Cp = df_BTC.copy()

In [130]:
# importation des bibliothèques nécessaires
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Ré-échantillonnage de la colonne 'Close' pour les données hebdomadaires et calcul de la moyenne
df_BTC_mean = df_BTC_Cp.resample('W').mean()

# Ajout d'une colonne 'Result' qui indique si le prix de fermeture de la semaine en cours est supérieur à celui de la semaine suivante
df_BTC_mean['Result'] = df_BTC_mean['Close'] > df_BTC_mean['Close'].shift(-1)

In [131]:
df_BTC_mean

Open          High           Low  \
Date                                                                  
2014-09-21 00:00:00+00:00    333.839777    339.878662    316.146161   
2014-09-28 00:00:00+00:00    321.413884    327.586400    312.610862   
2014-10-05 00:00:00+00:00    293.048606    298.779170    280.204640   
2014-10-12 00:00:00+00:00    274.388576    287.047193    267.375695   
2014-10-19 00:00:00+00:00    305.502315    312.188542    298.131326   
...                                 ...           ...           ...   
2022-12-25 00:00:00+00:00  15786.540318  15877.444057  15685.222098   
2023-01-01 00:00:00+00:00  15652.185407  15696.450893  15525.323940   
2023-01-08 00:00:00+00:00  15810.859515  15895.285714  15798.048270   
2023-01-15 00:00:00+00:00  17171.896624  17693.441964  17073.772321   
2023-01-22 00:00:00+00:00  19410.220215  19637.057129  19169.654297   

                                  Close     Adj Close        Volume  Result  
Date                                                                         
2014-09-21 00:00:00+00:00    324.329858    324.329858  2.441611e+07    True  
2014-09-28 00:00:00+00:00    319.654266    319.654266  2.089674e+07    True  
2014-10-05 00:00:00+00:00    286.932312    286.932312  3.144075e+07    True  
2014-10-12 00:00:00+00:00    280.593305    280.593305  3.846900e+07   False  
2014-10-19 00:00:00+00:00    306.296256    306.296256  1.759725e+07    True  
...                                 ...           ...           ...     ...  
2022-12-25 00:00:00+00:00  15789.893555  15789.893555  1.451878e+10    True  
2023-01-01 00:00:00+00:00  15605.315569  15605.315569  1.278807e+10   False  
2023-01-08 00:00:00+00:00  15882.261161  15882.261161  1.211592e+10   False  
2023-01-15 00:00:00+00:00  17613.962054  17613.962054  2.315064e+10   False  
2023-01-22 00:00:00+00:00  19389.207520  19389.207520  2.580721e+10   False  

[436 rows x 7 columns]

In [132]:
# Réinitialisation de l'index du DataFrame df_BTC_mean
df_BTC_mean.reset_index(inplace=True)

# Contient les 3 dernières lignes de "df_BTC_mean"
df_BTC_last = df_BTC_mean.tail(3)
df_BTC_last = df_BTC_last.drop(['Date','Result'], axis=1)

# Enlève les 3 dernières lignes de "df_BTC_mean"
df_BTC_mean = df_BTC_mean[:-3]

# Stock la colonne 'Result' dans la variable 'y'
y = df_BTC_mean['Result']

# Stockage les colonne contenues dans le DataFrame df_BTC_mean dans la variable 'X' en enlevant les colonnes Date et Result
X = df_BTC_mean.drop(['Date','Result'], axis=1)

In [133]:
df_BTC_mean

Date          Open          High           Low  \
0   2014-09-21 00:00:00+00:00    333.839777    339.878662    316.146161   
1   2014-09-28 00:00:00+00:00    321.413884    327.586400    312.610862   
2   2014-10-05 00:00:00+00:00    293.048606    298.779170    280.204640   
3   2014-10-12 00:00:00+00:00    274.388576    287.047193    267.375695   
4   2014-10-19 00:00:00+00:00    305.502315    312.188542    298.131326   
..                        ...           ...           ...           ...   
428 2022-12-04 00:00:00+00:00  16045.854632  16203.030971  15890.315011   
429 2022-12-11 00:00:00+00:00  16227.333705  16364.030273  16148.026507   
430 2022-12-18 00:00:00+00:00  16269.091936  16458.695731  16042.171177   
431 2022-12-25 00:00:00+00:00  15786.540318  15877.444057  15685.222098   
432 2023-01-01 00:00:00+00:00  15652.185407  15696.450893  15525.323940   

            Close     Adj Close        Volume  Result  
0      324.329858    324.329858  2.441611e+07    True  
1      319.654266    319.654266  2.089674e+07    True  
2      286.932312    286.932312  3.144075e+07    True  
3      280.593305    280.593305  3.846900e+07   False  
4      306.296256    306.296256  1.759725e+07    True  
..            ...           ...           ...     ...  
428  16101.038923  16101.038923  2.137547e+10   False  
429  16228.923968  16228.923968  1.757802e+10    True  
430  16208.876535  16208.876535  1.913591e+10    True  
431  15789.893555  15789.893555  1.451878e+10    True  
432  15605.315569  15605.315569  1.278807e+10   False  

[433 rows x 8 columns]

In [134]:
df_BTC_last

Open          High           Low         Close     Adj Close  \
433  15810.859515  15895.285714  15798.048270  15882.261161  15882.261161   
434  17171.896624  17693.441964  17073.772321  17613.962054  17613.962054   
435  19410.220215  19637.057129  19169.654297  19389.207520  19389.207520   

           Volume  
433  1.211592e+10  
434  2.315064e+10  
435  2.580721e+10

In [135]:
from sklearn.model_selection import train_test_split

# Séparer les données en ensemble d'entraînement et de test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [136]:
# Import de la classe KNeighborsClassifier de sklearn pour créer un modèle de classification basé sur les k plus proches voisins.
from sklearn.neighbors import KNeighborsClassifier

# Initialisation d'un modèle KNeighborsClassifier
model = KNeighborsClassifier()

# Entraînement du modèle sur les données d'entraînement
model.fit(X_train, y_train)

# Evaluation de la performance du modèle en utilisant les données de test
accuracy = model.score(X_test, y_test)
print("Accuracy: ", accuracy)

Accuracy:  0.5153846153846153


In [107]:
def invest(model, dataframe):
    for row in dataframe.values:
        print(model.predict(row.reshape(1,-1)))
        print(model.predict_proba(row.reshape(1,-1)))

In [108]:
invest(model, df_BTC_last)

[False]
[[0.6 0.4]]
[False]
[[0.6 0.4]]
[False]
[[0.6 0.4]]


C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\skl

In [78]:
# 2. Bagging

In [109]:
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier
# Initialisation d'un modèle de classification combiné appelé BaggingClassifier
# qui utilise un classificateur basé sur les plus proches voisins (KNeighborsClassifier) comme classificateur de base
# et 100 arbres de décision pour les combiner
model_Bagging = BaggingClassifier(base_estimator=KNeighborsClassifier(),
                         n_estimators=100)

# Entraînement du modèle sur les données d'entraînement
model_Bagging.fit(X_train, y_train)

# Evaluation de la performance du modèle en utilisant les données de test
accuracy = model_Bagging.score(X_test, y_test)
print("Accuracy: ", accuracy)

Accuracy:  0.5230769230769231


In [110]:
invest(model_Bagging, df_BTC_last)

C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but BaggingClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but BaggingClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but BaggingClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but BaggingClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but BaggingClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:45

[False]
[[0.632 0.368]]
[False]
[[0.69 0.31]]
[False]
[[0.538 0.462]]


In [80]:
# 3. Boosting

In [111]:
# Import de la classe AdaBoostClassifier de sklearn.ensemble
from sklearn.ensemble import AdaBoostClassifier

# Initialisation d'un objet model avec AdaBoostClassifier
# n_estimators est utilisé pour spécifier le nombre d'estimateurs (ou arbres de décision) utilisés dans l'algorithme
model_Boosting = AdaBoostClassifier(n_estimators=100)

# Entraînement du modèle sur les données d'entraînement
model_Boosting.fit(X_train, y_train)

# Evaluation de la performance du modèle en utilisant les données de test
accuracy = model_Boosting.score(X_test, y_test)
print("Accuracy: ", accuracy)

Accuracy:  0.5692307692307692


In [112]:
invest(model_Boosting, df_BTC_last)

[ True]
[[0.49948125 0.50051875]]
[False]
[[0.5006421 0.4993579]]
[False]
[[0.5006421 0.4993579]]


C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  warnings.warn(
C:\Users\devia.e15\Anaconda3\lib\site-packages\sklearn\base.